name: Unit Tests

on: [push]

jobs:
  build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Set up JDK 1.8
    uses: actions/setup-java@1
    with:
      java-version: 1.8
  - name: Set up Gradle
  - uses: gradle/gradle-build-action@v2
  - name: Run build with Gradle Wrapper
      run: ./gradlew build
  - name: Run Java tests
      run: ./gradlew test

  - name: Upload coverage reports to Codecov
    uses: codecov/codecov-action@v3
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}